# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: golem_app/golem_app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='golem_app/golem_app.proto',
  package='golem_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19golem_app/golem_app.proto\x12\tgolem_app\">\n\x11\x43reateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x18\n\x10task_params_json\x18\x02 \x01(\t\"\x11\n\x0f\x43reateTaskReply\"%\n\x12NextSubtaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"C\n\x10NextSubtaskReply\x12\x12\n\nsubtask_id\x18\x01 \x01(\t\x12\x1b\n\x13subtask_params_json\x18\x02 \x01(\t\"R\n\x0e\x43omputeRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsubtask_id\x18\x02 \x01(\t\x12\x1b\n\x13subtask_params_json\x18\x03 \x01(\t\"\x0e\n\x0c\x43omputeReply\"4\n\rVerifyRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsubtask_id\x18\x02 \x01(\t\"\x1e\n\x0bVerifyReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x13RunBenchmarkRequest\"\x13\n\x11RunBenchmarkReply2\xf0\x02\n\x08GolemApp\x12H\n\nCreateTask\x12\x1c.golem_app.CreateTaskRequest\x1a\x1a.golem_app.CreateTaskReply\"\x00\x12K\n\x0bNextSubtask\x12\x1d.golem_app.NextSubtaskRequest\x1a\x1b.golem_app.NextSubtaskReply\"\x00\x12?\n\x07\x43ompute\x12\x19.golem_app.ComputeRequest\x1a\x17.golem_app.ComputeReply\"\x00\x12<\n\x06Verify\x12\x18.golem_app.VerifyRequest\x1a\x16.golem_app.VerifyReply\"\x00\x12N\n\x0cRunBenchmark\x12\x1e.golem_app.RunBenchmarkRequest\x1a\x1c.golem_app.RunBenchmarkReply\"\x00\x62\x06proto3')
)




_CREATETASKREQUEST = _descriptor.Descriptor(
  name='CreateTaskRequest',
  full_name='golem_app.CreateTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_app.CreateTaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_params_json', full_name='golem_app.CreateTaskRequest.task_params_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=102,
)


_CREATETASKREPLY = _descriptor.Descriptor(
  name='CreateTaskReply',
  full_name='golem_app.CreateTaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=121,
)


_NEXTSUBTASKREQUEST = _descriptor.Descriptor(
  name='NextSubtaskRequest',
  full_name='golem_app.NextSubtaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_app.NextSubtaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=160,
)


_NEXTSUBTASKREPLY = _descriptor.Descriptor(
  name='NextSubtaskReply',
  full_name='golem_app.NextSubtaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_app.NextSubtaskReply.subtask_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_params_json', full_name='golem_app.NextSubtaskReply.subtask_params_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=229,
)


_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='golem_app.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_app.ComputeRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_app.ComputeRequest.subtask_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_params_json', full_name='golem_app.ComputeRequest.subtask_params_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=313,
)


_COMPUTEREPLY = _descriptor.Descriptor(
  name='ComputeReply',
  full_name='golem_app.ComputeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=329,
)


_VERIFYREQUEST = _descriptor.Descriptor(
  name='VerifyRequest',
  full_name='golem_app.VerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='golem_app.VerifyRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask_id', full_name='golem_app.VerifyRequest.subtask_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=383,
)


_VERIFYREPLY = _descriptor.Descriptor(
  name='VerifyReply',
  full_name='golem_app.VerifyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='golem_app.VerifyReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=415,
)


_RUNBENCHMARKREQUEST = _descriptor.Descriptor(
  name='RunBenchmarkRequest',
  full_name='golem_app.RunBenchmarkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=438,
)


_RUNBENCHMARKREPLY = _descriptor.Descriptor(
  name='RunBenchmarkReply',
  full_name='golem_app.RunBenchmarkReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=459,
)

DESCRIPTOR.message_types_by_name['CreateTaskRequest'] = _CREATETASKREQUEST
DESCRIPTOR.message_types_by_name['CreateTaskReply'] = _CREATETASKREPLY
DESCRIPTOR.message_types_by_name['NextSubtaskRequest'] = _NEXTSUBTASKREQUEST
DESCRIPTOR.message_types_by_name['NextSubtaskReply'] = _NEXTSUBTASKREPLY
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeReply'] = _COMPUTEREPLY
DESCRIPTOR.message_types_by_name['VerifyRequest'] = _VERIFYREQUEST
DESCRIPTOR.message_types_by_name['VerifyReply'] = _VERIFYREPLY
DESCRIPTOR.message_types_by_name['RunBenchmarkRequest'] = _RUNBENCHMARKREQUEST
DESCRIPTOR.message_types_by_name['RunBenchmarkReply'] = _RUNBENCHMARKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTaskRequest = _reflection.GeneratedProtocolMessageType('CreateTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETASKREQUEST,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.CreateTaskRequest)
  ))
_sym_db.RegisterMessage(CreateTaskRequest)

CreateTaskReply = _reflection.GeneratedProtocolMessageType('CreateTaskReply', (_message.Message,), dict(
  DESCRIPTOR = _CREATETASKREPLY,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.CreateTaskReply)
  ))
_sym_db.RegisterMessage(CreateTaskReply)

NextSubtaskRequest = _reflection.GeneratedProtocolMessageType('NextSubtaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEXTSUBTASKREQUEST,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.NextSubtaskRequest)
  ))
_sym_db.RegisterMessage(NextSubtaskRequest)

NextSubtaskReply = _reflection.GeneratedProtocolMessageType('NextSubtaskReply', (_message.Message,), dict(
  DESCRIPTOR = _NEXTSUBTASKREPLY,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.NextSubtaskReply)
  ))
_sym_db.RegisterMessage(NextSubtaskReply)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREQUEST,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.ComputeRequest)
  ))
_sym_db.RegisterMessage(ComputeRequest)

ComputeReply = _reflection.GeneratedProtocolMessageType('ComputeReply', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREPLY,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.ComputeReply)
  ))
_sym_db.RegisterMessage(ComputeReply)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYREQUEST,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.VerifyRequest)
  ))
_sym_db.RegisterMessage(VerifyRequest)

VerifyReply = _reflection.GeneratedProtocolMessageType('VerifyReply', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYREPLY,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.VerifyReply)
  ))
_sym_db.RegisterMessage(VerifyReply)

RunBenchmarkRequest = _reflection.GeneratedProtocolMessageType('RunBenchmarkRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNBENCHMARKREQUEST,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.RunBenchmarkRequest)
  ))
_sym_db.RegisterMessage(RunBenchmarkRequest)

RunBenchmarkReply = _reflection.GeneratedProtocolMessageType('RunBenchmarkReply', (_message.Message,), dict(
  DESCRIPTOR = _RUNBENCHMARKREPLY,
  __module__ = 'golem_app.golem_app_pb2'
  # @@protoc_insertion_point(class_scope:golem_app.RunBenchmarkReply)
  ))
_sym_db.RegisterMessage(RunBenchmarkReply)



_GOLEMAPP = _descriptor.ServiceDescriptor(
  name='GolemApp',
  full_name='golem_app.GolemApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=462,
  serialized_end=830,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTask',
    full_name='golem_app.GolemApp.CreateTask',
    index=0,
    containing_service=None,
    input_type=_CREATETASKREQUEST,
    output_type=_CREATETASKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NextSubtask',
    full_name='golem_app.GolemApp.NextSubtask',
    index=1,
    containing_service=None,
    input_type=_NEXTSUBTASKREQUEST,
    output_type=_NEXTSUBTASKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='golem_app.GolemApp.Compute',
    index=2,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='golem_app.GolemApp.Verify',
    index=3,
    containing_service=None,
    input_type=_VERIFYREQUEST,
    output_type=_VERIFYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunBenchmark',
    full_name='golem_app.GolemApp.RunBenchmark',
    index=4,
    containing_service=None,
    input_type=_RUNBENCHMARKREQUEST,
    output_type=_RUNBENCHMARKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOLEMAPP)

DESCRIPTOR.services_by_name['GolemApp'] = _GOLEMAPP

# @@protoc_insertion_point(module_scope)
